spring:
  application:
    name: LanJiBookstore
  mail:
    host: smtp.qq.com
    username: 
    password: 
  rabbitmq:
    addresses: 192.168.13.130
    username: guest
    password: guest
    virtual-host: /
  data:
    redis:
      host: 192.168.13.130
  datasource:
    url: jdbc:mysql://192.168.13.130:3306/lanji_bookstore
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: abcdrfghijk
      expire: 7
    filter:
      order: -100
  minio:
    endpoint: 'http://192.168.13.130:9000'
    username: 'minio'
    password: 'password'

jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR
  client:
    ts:
      path: /ts.zip
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: My Web Service
          description: |
            Restore the DTO explosion that was
            eliminated by server-side developers
          version: 1.0
